# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BabylonTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabylonTest
  pod 'RealmSwift'
  pod "ObjectMapper+Realm"
  pod 'Alamofire'
  
  target 'BabylonTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BabylonTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
